### PR TITLE
Adding insurance-pricing.dmn

### PR DESCRIPTION
**Pull request by kbowers-ibm**
Moving https://github.com/timwuthenow/dmn-workshop-labs/blob/master/policy-price/insurance-pricing.dmn to BAMOE repo

### CODE REVIEW

**Review by jomarko — COMMENTED** [review]
Thank you @kbowers-ibm . I noticed this this is still using `xmlns:kie="http://www.drools.org/kie/dmn/1.2"` what is kind of sign, it was created sing the DMN Classic editor, what is your opinion about storing the same diagram, the same logic, created by the new DMN Editor, it would be then stored as DMN 1.5. Is there some limitation from doing it. Do we reference this code example in a section, where the DMN Classic editor is used? Or I do not know, there may be some limitation I do not see on the first sight.

**Comment by kbowers-ibm** [comment]
Updated thanks @jomarko!

**Comment by kbowers-ibm** [comment]
>  Do we reference this code example in a section, where the DMN Classic editor is used?

Should be fine, I just need to update the screenshots to use the new DMN Editor tomorrow!

**Review by jomarko — COMMENTED** [review]
Thank you @kbowers-ibm , I tried to import the given file into the new DMN Editor and I think it actually does more changes in the `<dmn:definitions>` tag. So probably we could upload a fresh `insurance-pricing.dmn` created using KIE tooling.

If you take a look at the existing file, the occurrences of the `trisotech` suggest, the file was not created using kie tooling.

I created such file (insurance-pricing-2.dmn) here https://gist.github.com/jomarko/a8c6f07d24d673de539125a7aeb17875

**Comment by kbowers-ibm** [comment]
Updated based on your new file, appreciate the help @jomarko!

**Review by jomarko — APPROVED** [review]
Thank you @kbowers-ibm

**Pull request merged**
